apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelupdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: levelupdevops
  template:
    metadata:
      labels:
        app: levelupdevops
        version: IMAGE_LABEL
    spec:
      containers:
      - name: levelupdevops
        image: ACR_URL/levelupdevops:IMAGE_LABEL
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # TODO: move this to a secret
        - name: ConnectionStrings__MyDB
          value: "Server=AzureSqlDatabase;Database=..."
---
apiVersion: v1
kind: Service
metadata:
  name: levelupdevops
spec:
  type: NodePort
  selector:
    app: levelupdevops
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: levelupdevops
  labels:
    name: levelupdevops
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - levelupdevops.AKS_URL
    secretName: tls-secret
  rules:
  - host: levelupdevops.AKS_URL
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: levelupdevops
            port:
              number: 5000
