name: Docker build and push

on:
  push:
    branches: main

jobs:


  #login to docker
  login:
    runs-on: ubuntu-latest
    steps:
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#build and push image to docker.
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker build
        run: |
          docker build --tag ${{ vars.DOCKERHUB_USERNAME }}/dotnet-app:${{github.sha}} 

          docker push ${{ vars.DOCKERHUB_USERNAME }}/dotnet-app:${{github.sha}}

        



  

  